apiVersion: v1
kind: Service
metadata:
  name: expenses-app
spec:
  type: NodePort
  selector:
    app: expenses-app
  ports:
    - name: appservice-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
